Update dependencies
bennypowers/lit-css pull request #47
Opened 2023-10-20 09:50 UTC by sledsworth

I opened this mainly to update `esbuild` dependency to support `0.19.x`.

I updated all minor and patches, as well as `lit` while I was at it.

2023-10-20 09:53 UTC, bennypowers commented on package.json
> +    "lit": "^3.0.0",
This should maybe be a peerdep range so as to support lit 2 as well

2023-10-23 17:22 UTC, eatsjobs commented
any chance to have this one merged?

2023-10-23 17:24 UTC, bennypowers requested changes
looks good, just please revert the whitespace changes, then we'll be ready to go

2023-10-23 17:39 UTC, bennypowers approved these changes
Thank you very much for the PR

2023-10-23 17:40 UTC, merged